project_id = "cquzezvwadszynzbcbso"

[functions.ai-reading]
verify_jwt = true

[functions.bazi-calculate]
verify_jwt = true

[functions.create-stripe-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
