project_id = "cquzezvwadszynzbcbso"

[functions.ai-reading]
verify_jwt = true

[functions.bazi-calculate]
verify_jwt = true

[functions.create-stripe-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.custom-question-answer]
verify_jwt = true

[functions.ai-chat]
verify_jwt = true

[functions.process-referral]
verify_jwt = false

[functions.fengshui-analysis]
verify_jwt = true

